import cv2
print(cv2.__version__)
img = cv2.imread(".jpg",0)
print("IMAGE")
print(img)
print("+=TYPE OF IMAGE=+")
print(type(img))
print('+=IMAGE SHAPE++=')
print(img.shape)
print("====IMAGE 0TH INDEX===")
print(img[0])
print("==IMAGE SHAPE 0TH INDEX== ")
print(img[0].shape)
print("==IMAGE SHAPE ")
